### ISSUE TITLE
Some Typos

### ISSUE THREAD

**Issue by linhaowei1** [lancopku/Avg-Avg#2]
Hello Sishuo,

I hope this message finds you well. I wanted to bring to your attention a few typos I noticed in this repository:

1. The datasets "Jigsaw" and "Twitter" seem to be missing from the Google Drive. Will you upload them?

2. (In the README.md file) For the command under **Other Algorithms**, it should be `--pretrained_model` instead of `--pretraiend_model`.

3. (In the README.md file) For the command under **Test**, it should be `--input_dir` instead of `--inpur_dir`.

Thank you for your attention to these matters. BTW, this repo is good!

**Comment by PKUCSS** [comment]
@linhaowei1 Hello Haowei, thanks for your attention and kind suggestions. I'll fix the typos and provide the links to Jigsaw and Twitter datasets in the coming days for the convenience of the peers interested in using my repo. Thank you very much.

**Comment by PKUCSS** [comment]
@linhaowei1 I have done the jobs according to your advice. Thank you again and please let me know if you have other questions.
